### ISSUE TITLE
OK stops running within a test case at first failed line

### ISSUE THREAD

**Issue by knrafto** [okpy/ok-client#240]
Requested by @jalagar 

Let's say I have

```
>>> factorial(4)
24
>>> factorial(5)
120
>>> factorial(0)
0

# Error: expected
#     1
# but got
#     0
```

Let's say I modify `factorial` to print its argument. Right now I will get

```
>>> factorial(4)
4
24

# Error: expected
#     24
# but got
#     4
#     24
```

but I was only concerned about the last case.

We could:
- By default, run all doctest lines, and print an error for each one:

```
>>> factorial(4)
4
24

# Error: expected
#     24
# but got
#     4
#     24

>>> factorial(5)
5
120

# Error: expected
#     120
# but got
#     5
#     120

>>> factorial(0)
0
0

# Error: expected
#     1
# but got
#     0
#     0
```

this seems a little verbose.
- By default, run all doctest lines, and print only the first failure:

```
>>> factorial(4)
4
24

# Error: expected
#     10
# but got
#     4
#     24

>>> factorial(5)
5
120
>>> factorial(0)
0
0
```
- By default, run all doctest lines, and print only the first failure, but at the end:

```
>>> factorial(4)
4
24
>>> factorial(5)
5
120
>>> factorial(0)
0
0

# Error: for `factorial(5)`, expected
#     24
# but got
#     4
#     24

```

it might be difficult to indicate exactly which line failed, however (we don't have line numbers, and there could be repeated lines).
- Add another flag to modify the behavior to run everything and not check whether it is correct (i.e. no error messages). Students will not probably know this flag exists, however.

What do you guys think?

**Comment by Sumukh** [comment]
Isnt this what ok -v is for?

**Comment by knrafto** [comment]
Do you mean that `-v` does this behavior already or that co-opt `-v` to do this as well?

I just checked, and with `-v` it stops at the first failing doctest (within one test case that is). And I think we should keep `--verbose` meaning "print more output", instead of changing how a test case is run.

**Comment by Sumukh** [comment]
This was a common request. 

I see - it stops within the test case. A new option sounds like a good idea: Maybe `--all`?

**Comment by knrafto** [comment]
`--all` already exists. I'd prefer not to add a new flag though, because students generally don't use flags, and we want to keep printf debugging accessible to students who aren't familiar with the command line. It should be a last resort if we can't figure out a good default way to display failing tests.

**Comment by knrafto** [comment]
I think the "By default, run all doctest lines, and print only the first failure" option is the best, but we need some more real-world testing after it's implemented to see if it'll work. I'm concerned that long tracebacks will hide the error message.

**Comment by Sumukh** [comment]
Or we could flood them with output: 
```
>>> factorial(4)
4
24

# Error: expected
#     10
# but got
#     4
#     24

>>> factorial(5)
5
120

# Error: expected
#     120
# but got
#     5
#     120

>>> factorial(0)
0
0


# Error: expected
#     0
# but got
#     0
#     0

First Failure: 

>>> factorial(4)
4
24

# Error: for `factorial(5)`, expected
#     24
# but got
#     4
#     24

**Comment by knrafto** [comment]
Looks like we're doing Sumukh's proposal. That is
* Any failed doctest line, print out the error message
* If some line _other than the last line_ failed, reprint that error message at the end as the "first failure".

**Comment by kavigupta** [comment]
I think the `print("DEBUG:", )` feature largely makes this request redundant, as now students can pass test cases with debug output
