### ISSUE TITLE
Provide more helpful error message when failing to load assignment

### ISSUE THREAD

**Issue by epai** [okpy/ok-client#324]
Instead of saying `Error loading assignment:  Error importing file hw02.py`, a more helpful message would bestsellers something like `Error loading assignment:  Check for syntax and/or indentation errors in hw02.py`.

![snip20170904_18](https://user-images.githubusercontent.com/8680381/30045788-2339d560-91bb-11e7-8d16-29a3a5a04b52.png)

**Comment by addcninblue** [comment]
How do you reproduce this behavior? I don't have the "Error importing file...". Attached is a screenshot:
![image](https://user-images.githubusercontent.com/7519521/34317821-e5738a26-e76b-11e7-9c0e-546970b0e2d2.png)

**Comment by kavigupta** [comment]
Could not repro on my machine either, I think this has been fixed
