### ISSUE TITLE
Don't error out if no tests loaded

### ISSUE THREAD

**Issue by SamLau95** [okpy/ok-client#327]
In DS100 we write cells containing `assert` statements in the master version of our notebooks. Our build system then takes those cells and automatically generates OkPy tests.

This means that for our master notebook there are no OkPy tests to load. However, we're forced to have some placeholder test there (eg. `q_placeholder.py`) so that the config will load.

Is it possible to have the client not throw an exception when no tests are loaded? I think a warning would suffice for our purposes.

**Comment by SamLau95** [comment]
@epai any opinions on this?

**Comment by kavigupta** [comment]
I believe this should have been resolved by https://github.com/okpy/ok-client/pull/392. Sorry for the late fix!
