### ISSUE TITLE
Detect when a notebook has been renamed and provide a clearer error message

### ISSUE THREAD

**Issue by davidwagner** [okpy/ok-client#352]
We're using okpy in Jupyter notebooks in Data 8, and the submit call has `_ = ok.submit()`.

Sometimes students rename the notebook.  If they do that, submitting fails in a non-obvious way.  In particular, one gets a result like

```
Saving notebook.... Could not save your notebook. Make sure your notebook is saved before sending it to OK!
Submit... 100% complete
Submission successful for user: x
URL: https://okpy.org/cal/data8/fa18/...
```

and a blank notebook is submitted to okpy.

This is undesirable, because it's easy for students to not realize that something has gone wrong.  Yes, it says "Could not save", but it also says "Submission successful", and we've had several students who thought everything was fine.

Better would be to avoid displaying "Submission successful" if the notebook could not be saved, as that can be very misleading.

Best would be to do that, plus also detect that the notebook has been renamed (the filename doesn't match the `src` attribute in the `.ok` file) and explicitly warn the student that the name seems wrong and that they should avoid renaming the file.

**Comment by ja5087** [comment]
From some testing this only happens when a notebook with the original name exists (possibly blank), but the student is working off a file with a different name. If the file with the original name doesn't exist then a fairly descriptive FileNotFound error is thrown by python.
