### ISSUE TITLE
Support saving in Jupyter Lab

### ISSUE THREAD

**Issue by papajohn** [okpy/ok-client#359]
Jupyter Lab is the revised interface for Jupyter notebooks.

https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906

The `.submit()` method run within a notebook saves the current notebook and then submits it, but the save operation is not compatible with Jupyter Lab.

![screen shot 2019-01-16 at 8 59 51 am](https://user-images.githubusercontent.com/320145/51265154-fa6b2900-196c-11e9-8fa9-2f7cf1d3d7a7.png)

Everything else seemed to work fine out-of-the-box when running an assignment notebook in Jupyter Lab.

**Comment by ja5087** [comment]
I can work on this

**Comment by ja5087** [comment]
Turns out JupyterLab removed the ability to inject arbitrary JavaScript, which we relied on for programmatically saving without user input (see [link](https://github.com/jupyterlab/jupyterlab/issues/3118)). Furthermore, the IPython object is not accessible anymore. I'm looking into how we can support saving a different way.

**Comment by ja5087** [comment]
The issue lies where JupyterLab has moved away from exposing public JavaScript APIs. The official recommended way is to write an extension to support additional behavior. I will research into what our options are.

**Comment by ja5087** [comment]
Okay, this pull request should support saving in JupyterLab. The solution is to directly trigger the frontend save button's click() method with the following snippet: `document.querySelector('[data-command="docmanager:save"]').click();'`

I've also added code to allow selection of each mode via a parameter (default is normal Jupyter Notebook). The reason this isn't done in code is it's difficult to determine reliably which frontend an IPython kernel is running inside.
