### ISSUE TITLE
When authentication fails it should tell you to try `--authenticate --no-browser`

### ISSUE THREAD

**Issue by kavigupta** [okpy/ok-client#363]
This error:

![image](https://user-images.githubusercontent.com/3214932/53548032-66e95400-3ae5-11e9-8d8d-7161c3c1f3f4.png)

is almost always fixed by running `python ok --authenticate --no-browser`. We should just put that in the error message.

**Comment by kaitlynlee** [comment]
Will try to fix

**Comment by mehrdadn** [comment]
Hmm, #356 should have fixed this... wondering why it didn't.

**Comment by mehrdadn** [comment]
I'm looking into this and it really seems like this shouldn't be happening—perhaps the student had an old version of OkPy somehow, or the server isn't running?

To see what I mean, go to `protocols/backup.py` and replace `send_messages(access_token, ...)` with `send_messages("dummy", ...)`, and run OkPy in debugging mode via `python3 ok --submit --debug`.

You'll see my [re-authentication](/okpy/ok-client/pull/356/files#diff-c8946fe1d46c94203ea98dccfa6cd23eR220) code gets [triggered](/okpy/ok-client/pull/356/files#diff-23ebfefa6f7bb396ed46948eec48c92bR182). (Press Ctrl+C to quit.)

Now scroll up a bit and notice the error is exactly the same one that the student sees:

    WARNING  | backup.py:179 | HTTPError error message: The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

Hence I simply don't see how this code could _not_ be running, unless for some reason the student had an old version of OkPy (which is possible if the server wasn't building the latest version for whatever reason).

@kavigupta: Next time you see this error, can you ask the student to run with `--debug` next time and send you (or me) the log so I can see what's happening?

**Comment by kavigupta** [comment]
Ok looks like this hasn't really come up. I will assume this is fixed
