### ISSUE TITLE
Better error message when question is accidentally deleted

### ISSUE THREAD

**Issue by itsnshaw** [okpy/ok-client#364]
There should be a better error message when a student accidentally deletes one of the required questions for an assignment. 

For example, a student missing the balanced question in a homework assignment
![image](https://user-images.githubusercontent.com/33583144/53670681-5ee9fb00-3c30-11e9-8dde-f9462485ac4e.png)
is not very descriptive for students.

**Comment by ja5087** [comment]
Will work on this

**Comment by ja5087** [comment]
Is there a reliable way to reproduce this? A specific assignment or example

**Comment by kavigupta** [comment]
Is this better @itsnshaw ?

```
=====================================================================
Assignment: Lab 7
OK, version v1.14.19
=====================================================================

Error loading assignment: Required question(s) missing: aqscale. This often is the result of accidentally deleting the question's doctests or the entire function.
Checking for software updates...
Network error when checking for updates.
```
