### ISSUE TITLE
Add coloring to error messages

### ISSUE THREAD

**Issue by averyyip** [okpy/ok-client#387]
We have been seeing problems with jupyter notebooks not submitting successfully and students not knowing their submission failed. It would be great if we can add a red coloring to the failure message so they would know about the failure and contact their GSIs.

Coloring Guide: https://stackoverflow.com/questions/287871/how-to-print-colored-text-in-terminal-in-python

Line Reference:
https://github.com/okpy/ok-client/blob/6ede08db160b45842565e49846294e8dd27b8017/client/api/notebook.py#L121

**Comment by kavigupta** [comment]
We should probably use https://stackoverflow.com/questions/287871/how-to-print-colored-text-in-terminal-in-python/3332860#3332860 since we have to support Windows but this seems like a great idea!

**Comment by mehrdadn** [comment]
Yeah, just use `colorama`, it takes care of auto-detecting the terminal and everything.

**Comment by kavigupta** [comment]
Resolved by https://github.com/okpy/ok-client/pull/400
