### ISSUE TITLE
Make submission prompt school agnostic

### ISSUE THREAD

**Issue by TylerADavis** [okpy/ok-client#408]
Currently, calling `ok.submit()` for the first time prints `Please enter your bCourses email`. If okpy is being used at another school, this could confuse students as they don't know bCourses.

Perhaps this could be set in a configuration somehow? Either in the `.ok` file or in the notebook

**Comment by Sumukh** [comment]
👍 This is a good idea. Perhaps we should just change it to `your school email` for now if it's too hard to dynamically figure this out from theenvironmentt / config

**Comment by TylerADavis** [comment]
Maybe specifically mention `.edu`, but I like the sound of that
