### ISSUE TITLE
ERROR: datascience 0.15.3 has requirement coverage==4.5.3, but you'll have coverage 4.4 which is incompatible

### ISSUE THREAD

**Issue by tbrown122387** [okpy/ok-client#410]
` pip install datascience` yields

`ERROR: datascience 0.15.3 has requirement coverage==4.5.3, but you'll have coverage 4.4 which is incompatible.`

It isn't a fatal error, but it confuses students.

**Comment by addcninblue** [comment]
Hey Professor Taylor,

I believe this is an issue regarding the [datascience module](https://github.com/data-8/datascience), so an issue can be raised there. I will be resolving this for the time being unless there is some other issue I missed.

Thanks!
Addison

**Comment by tbrown122387** [comment]
Right, datascience not okpy. Apologies. I remember submitting a pull request to them earlier this year but I guess they have t sorted it out yet. Thanks.
