### ISSUE TITLE
How can students add tests?

### ISSUE THREAD

**Issue by papajohn** [okpy/ok-client#63]
We should have some standard way for students to write their own tests. One obvious option is to have them add a new function in their source file that has doctests, and make an option for `ok` to run those doctests (even if they aren't specified in the `.ok` file).

**Comment by epai** [comment]
@khalilsarwari implemented a way for students to add tests in a separate `student_tests.rst` file, but having a way to make tests using doctests would be good too.  I'll keep this issue open for now until we develop a solution for doctests

**Comment by kavigupta** [comment]
They can just run doctests for any function in a file marked for doctests, all the tests are created, regardless of whether they are used.
