### ISSUE TITLE
Client side confirmation of submission after deadline

### ISSUE THREAD

**Issue by Sumukh** [okpy/ok-client#68]
Have we thought of adding a warn_date to the assignments `.ok` file - and if the current time it confirms before sending in a submission? (Similar to glookup's late submission) 

A related issue is actually displaying helpful error messages. The server currently can send helpful error messages. Displaying more than just the "Check your network connectivity" that is displayed now on errors would make things clear for students.

**Comment by albert12132** [comment]
@Sumukh , we talked a few weeks ago about implementing this, and I think it would be a great feature. Can you elaborate on your ideas for this issue? In particular, I was interested in the following:

* Warning for late submissions (the due date can be included in the `.ok` file
* Listing partners in the group

**Comment by Sumukh** [comment]
These both rely on the server responding with more information which will require minor server changes. 

- Due Date: ok should confirm with users that they want to submit - even though the deadline has passed. (This would be similar to the `submit` tool)

Implementation: Include a unix time for the due date in the .ok file - if the users run the `--submit` flag after the deadline - it will prompt to make sure that they want to submit X hours after the deadline. They type in yes/no to confirm. If yes: We then proceed as normal. 

The server should also respond with whether the submission was marked as late - to prevent tampering and for completeness. 

The prompts can be the same as the existing `submit` tool.  

> python3 ok --submit 
   The deadline has passed (+2 hours).
   Are you sure you want to submit (Yes/No): Yes
   ... 
   Late submission of Hog (+2 Hours)
   ... 

- Listing partners: The server response for a submission can include what email it was submitted to and the other members of the submitters group. This would just be another attribute of the server response. The client would just have to display that information 

> Submission of Hog at 11:09PM 
   URL: 
   Submitted by: submitter@student.com
   Group: (Either No Group or partner0@student.com, partner2@student.com)

**Comment by kavigupta** [comment]
Oh this is actually resolved incidentally by https://github.com/okpy/ok-client/pull/420
